name: Manual
on:
  workflow_dispatch:
    inputs:
      log-level:
        type: choice
        required: true
        options:
          - info
          - warn
          - error
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.log-level }}"