name: Change shell
on:
  push:
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: echo "${BASH}"
      - shell: python
        run: |
          import os
          print(os.environ['PATH'])
