name: koko-ga-github-workflow-nandesu
on:
  push:
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          REF: ${{ github.ref }}
        run: echo "${REF}"
