name: Cross repo
on: push
env:
  TARGET_REPO: baki_char
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: create
        run: ./.github/scripts/token.sh
        env:
          APP_ID: ${{ secrets.APP_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          repository: wonda-tea-coffee/${{ env.TARGET_REPO }}
          path: ${{ env.TARGET_REPO }}
          token: ${{ steps.create.outputs.token }}
      - run: cat "${TARGET_REPO}/README.md"
